version: '3'
services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./test_db:/test_db
    ports:
      - "3306:3306"
    networks:
      - my-network

  jupyter:
    image: jupyter/datascience-notebook:latest
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
